// Generated by CoffeeScript 1.8.0
(function() {
  var ProviderLoginDetails, User, assert, models, _ref;

  models = (_ref = require("../models"), User = _ref.User, ProviderLoginDetails = _ref.ProviderLoginDetails, _ref);

  assert = require("chai").assert;

  beforeEach(function(done) {
    var k, v;
    return knexion.raw("TRUNCATE TABLE " + (((function() {
      var _results;
      _results = [];
      for (k in models) {
        v = models[k];
        _results.push(v.tableName);
      }
      return _results;
    })()).join(',')) + " RESTART IDENTITY").then(done());
  });

  describe('User model tests', function() {
    return it('autoincrements id, insert and fetchAll work', function(done) {
      var user;
      user = new User();
      return user.save(null, {
        method: "insert"
      }).then(function(model) {
        assert(model.id === 1);
        return (new User()).save(null, {
          method: "insert"
        }).then(function(m2) {
          assert(m2.id === 2);
          return User.fetchAll().then(function(res) {
            assert(res.models.length === 2);
            return done();
          });
        });
      });
    });
  });

  describe('Truncate worked', function() {
    return it('has no Users', function(done) {
      return User.fetchAll().then(function(res) {
        assert(res.models.length === 0);
        return done();
      });
    });
  });

  describe('Transaction', function() {
    it('rolls back on error', function(done) {
      var tx;
      tx = bookshelf.transaction(function(t) {
        return (new User).save(null, {
          method: "insert",
          transacting: t
        }).then(function(m1) {
          return (new User).save({
            oops: "nope"
          }, {
            method: "insert",
            transacting: t
          }).then(function() {});
        });
      });
      return tx["catch"](function(err) {
        return User.fetchAll().then(function(res) {
          assert(res.models.length === 0);
          return done();
        });
      });
    });
    return it('succeeds when no error', function(done) {
      var tx;
      tx = bookshelf.transaction(function(t) {
        return (new User).save(null, {
          method: "insert",
          transacting: t
        }).then(function(m1) {
          return (new User).save(null, {
            method: "insert",
            transacting: t
          }).then(function(m2) {});
        });
      });
      return tx.then(function() {
        return User.fetchAll().then(function(res) {
          assert(res.models.length === 2);
          return done();
        });
      });
    });
  });

  describe('User has many ProviderLoginDetails', function() {
    return it('User.logins returns ProviderLoginDetails', function(done) {
      return (new User).save(null, {
        method: "insert"
      }).then(function(user) {
        var pld;
        pld = new ProviderLoginDetails({
          id: "razzafrazza",
          provider: "github",
          data: '{"some": "thing"}',
          user_id: user.id
        });
        return pld.save(null, {
          method: "insert"
        }).then(function(new_pld) {
          return new_pld.user().fetch().then(function(reluser) {
            var _ref1;
            assert((reluser.get('id') === (_ref1 = user.id) && _ref1 === 1));
            return reluser.logins().fetch().then(function(plds) {
              assert(plds.models[0].get('id') === 'razzafrazza');
              return done();
            });
          });
        });
      });
    });
  });

}).call(this);
