// Generated by CoffeeScript 1.8.0
(function() {
  var knex;

  knex = require('knex')({
    client: 'postgres',
    connection: {
      host: '127.0.0.1',
      user: process.env.PG_USER,
      password: process.env.PG_PASSWORD,
      database: 'csm',
      charset: 'utf8'
    },
    debug: true
  });

  module.exports.knex = knex;

}).call(this);
