// Generated by CoffeeScript 1.8.0
(function() {
  var c, l, m;

  require("./conn");

  m = require("./models");

  c = function(model) {
    return knexion.schema.createTableIfNotExists(model.tableName, model.createTable);
  };

  l = console.log;

  c(m.User).then(function() {
    l("User created");
    c(m.ProviderLoginDetails).then(function() {
      return l("ProviderLoginDetails created");
    });
    return c(m.App).then(function() {
      l("App created");
      return c(m.ProviderIDSecret).then(function() {
        l("ProviderIDSecret created");
        return c(m.Container).then(function() {
          l("Container created");
          return process.exit();
        });
      });
    });
  });

}).call(this);
