// Generated by CoffeeScript 1.8.0
(function() {
  var Model, created, name, s, _ref;

  require("./conn");

  created = 0;

  _ref = require("./models");
  for (name in _ref) {
    Model = _ref[name];
    created += 1;
    s = knexion.schema.createTableIfNotExists(Model.tableName, Model.createTable).then(function(a, b, c) {
      created -= 1;
      if (created === 0) {
        return process.exit();
      }
    });
  }

}).call(this);
