// Generated by CoffeeScript 1.8.0
(function() {
  var ProviderLoginDetails, User, github_complete, _ref;

  _ref = require("./models"), User = _ref.User, ProviderLoginDetails = _ref.ProviderLoginDetails;

  github_complete = function(result) {
    var trans;
    trans = bookshelf.transaction(function(t) {
      var model, uid;
      uid = result.user_data.id;
      model = {
        id: uid,
        provider: "github"
      };
      return new ProviderLoginDetails(model).fetch(null, {
        transaction: t
      }).then(function(m) {
        var user;
        if (m === null) {
          user = new User();
          return user.save(null, {
            method: "insert",
            transacting: t
          }).then(function(user) {
            var pld;
            model.user_id = user.id;
            pld = new ProviderLoginDetails(model);
            return pld.save({
              data: result.user_data
            }, {
              method: "insert",
              transacting: t
            }).then(function() {});
          });
        } else {

        }
      });
    });
    return trans["catch"](function(err) {
      return err;
    });
  };

  module.exports.github_complete = github_complete;

}).call(this);
