// Generated by CoffeeScript 1.8.0
(function() {
  var client, redis;

  redis = require("redis");

  client = redis.createClient(process.env.REDIS_PORT_6379_TCP_PORT || '6379', process.env.REDIS_PORT_6379_TCP_ADDR || 'localhost', process.env.REDIS_OPTIONS ? JSON.parse(process.env.REDIS_OPTIONS) : {});

  global.redis_client = client;

}).call(this);
