// Generated by CoffeeScript 1.8.0
(function() {
  var app, express, oauth, server;

  express = require('express');

  app = express();

  oauth = require('oauth-express');

  app.get('/auth/:provider', oauth.handlers.auth_provider_redirect);

  app.get('/auth_callback/:provider', oauth.handlers.auth_callback);

  oauth.emitters.github.on('complete', require("./oauth-events").github_complete);

  app.use("/public", express["static"]("" + __dirname + "/public"));

  app.use("/lib", express["static"]("" + __dirname + "/bower_components"));

  app.use("/", express["static"]("" + __dirname + "/views"));

  server = app.listen(4000, function() {
    return console.log('Listening on port %d', server.address().port);
  });

  module.exports.app = app;

}).call(this);
