// Generated by CoffeeScript 1.8.0
(function() {
  window.OAuth = {
    calls: {
      initialize: 0,
      setOAuthdURL: 0,
      popup: 0
    },
    initialize: function() {
      return this.calls.initialize += 1;
    },
    setOAuthdURL: function() {
      return this.calls.setOAuthdURL += 1;
    },
    popup: function(provider, cb) {
      this.calls.popup += 1;
      return cb(null, {
        access_token: "ABC"
      });
    }
  };

  describe('anything', function() {
    beforeEach(module('CSMApp'));
    beforeEach(inject(function($controller, $rootScope) {
      var ctrl, scope;
      scope = $rootScope.$new();
      return ctrl = $controller('CSMController', {
        $scope: scope
      });
    }));
    return it('calls OAuth.popup on github login', function(done) {
      assert.equal(scope.$storage.github_access_token, void 0);
      scope.github_login();
      assert.equal(OAuth.calls.popup, 1);
      assert.equal(scope.$storage.github_access_token, "ABC");
      return done();
    });
  });

}).call(this);
